### PR TITLE
Display the current user's gists and filter by public, starred, and forked

### LINKED ISSUE #26: Get authenticated user Gists
List of the authenticated user Gists.
- Public
- Starred
- Forked

### PR DESCRIPTION
**Pull request by filipewl**
Closes #26.

jsmllpjwdx

---

Also, display a label if the gist is secret.

### CODE REVIEW

**Comment by enderahmetyurt** [comment]
@filipewl great! I will check all of them.

**Comment by shivanibhanwal** [comment]
Yes after too many requests we will get 403 error if user really hit too
many gists.
We need to even capture that error.

Thanks
Shivani Thakur
*http://www.kiprosh.com* <http://www.kiprosh.com/>
*https://in.linkedin.com/pub/shivani-thakur-daxini/6/671/0*
<https://in.linkedin.com/pub/shivani-thakur-daxini/6/671/0>

**Comment by enderahmetyurt** [comment]
@filipewl for now, we can drop the fork feature. When we find a better solution we can add later.

On another way, I guess we need a cache mechanism. I did but I think it's not working. API requests like getting followers, followings and their gists should be cached for 1 hour or 30 minutes. Otherwise, as you told we will exceed the API request limit.

For that PR, we should disable fork Gists. Just fetching what API returns.

**Comment by filipewl** [comment]
@enderahmetyurt, later I'll send a PR to remove the **Forked** page.

**Comment by enderahmetyurt** [comment]
I did it :)

**Pull request merged**
