### PR TITLE
Add syntax highlight to a gist's file when creating one

### PR DESCRIPTION
**Pull request by filipewl**
Follow up for https://github.com/enderahmetyurt/gistcatch/pull/29.

hrxsogh334

I setup CodeMirror for the highlight, it's the same library used by gist. This demo of dynamically loading the language modes helped me with the implementation: https://codemirror.net/demo/loadmode.html

I opted for updating the highlight with a button because it seemed faster than on keypress.

There are commits from https://github.com/enderahmetyurt/gistcatch/pull/29 because I needed the changes in `gists/create` branch... In reality there were only [3 commits of difference](https://github.com/filipewl/gistcatch/pull/1). The most important logic is in [codemirror_toggle.js](https://github.com/filipewl/gistcatch/blob/68eb78dedb5af19bd9575f7b7cfa5030abee35ca/app/assets/javascripts/codemirror_toggle.js).

You will noticed lots of files in `vendor/assets/javascripts/codemirror/modes`. That seemed necessary to dynamically load the language syntaxes. They are loaded on demand, so it shouldn't be a problem.

### CODE REVIEW

**Comment by enderahmetyurt** [comment]
Hmm, There are lots of files. It seems weird. For now, I cannot merge it.

**Comment by filipewl** [comment]
> Hmm, There are lots of files. It seems weird. For now, I cannot merge it.

Yeah, I know... I pulled all language modes available at https://github.com/codemirror/CodeMirror/tree/master/mode.

Which languages do you want to support? I can leave only the chosen ones.

**Comment by filipewl** [comment]
@enderahmetyurt, for now I left only syntax highlight for the following extensions: CSS, HTML, JS, Ruby, and Markdown.

**Comment by enderahmetyurt** [comment]
You should be right but I guess for now we can wait. If the users warn us about syntax highlighting we can add that feature. What do you think? @filipewl

**Comment by shivanibhanwal** [comment]
@filipewl  why did not you utilized same `Rouge` Syntax highlighter which we have in the repo? 
http://rouge.jneen.net/

**Comment by filipewl** [comment]
> You should be right but I guess for now we can wait. If the users warn us about syntax highlighting we can add that feature. What do you think? @filipewl

@enderahmetyurt, I agree. We can put this one on hold then.

> @filipewl why did not you utilized same `Rouge` Syntax highlighter which we have in the repo?
> [http://rouge.jneen.net](http://rouge.jneen.net/)
> cc: @enderahmetyurt

@shivanibhanwal, I noticed we were using something to display the gist's files with syntax highlight, but it seemed to me that it only worked when displaying the content, rendered from the server in `<pre></pre>` tags.

For this specific case, I wanted something that could work with a `textarea` in the client-side so the user could have the syntax highlight while creating the gist.

**Comment by filipewl** [comment]
Closing as [mentioned before](https://github.com/enderahmetyurt/gistcatch/pull/30#issuecomment-435016630).

**Pull request closed without merging**
